// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: server/api/proto/queue/v1/queue.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueStatus int32

const (
	QueueStatus_QUEUE_STATUS_UNSPECIFIED QueueStatus = 0
	QueueStatus_QUEUE_STATUS_WAITING     QueueStatus = 1
	QueueStatus_QUEUE_STATUS_READY       QueueStatus = 2
	QueueStatus_QUEUE_STATUS_EXPIRED     QueueStatus = 3
	QueueStatus_QUEUE_STATUS_COMPLETED   QueueStatus = 4
)

// Enum value maps for QueueStatus.
var (
	QueueStatus_name = map[int32]string{
		0: "QUEUE_STATUS_UNSPECIFIED",
		1: "QUEUE_STATUS_WAITING",
		2: "QUEUE_STATUS_READY",
		3: "QUEUE_STATUS_EXPIRED",
		4: "QUEUE_STATUS_COMPLETED",
	}
	QueueStatus_value = map[string]int32{
		"QUEUE_STATUS_UNSPECIFIED": 0,
		"QUEUE_STATUS_WAITING":     1,
		"QUEUE_STATUS_READY":       2,
		"QUEUE_STATUS_EXPIRED":     3,
		"QUEUE_STATUS_COMPLETED":   4,
	}
)

func (x QueueStatus) Enum() *QueueStatus {
	p := new(QueueStatus)
	*p = x
	return p
}

func (x QueueStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_server_api_proto_queue_v1_queue_proto_enumTypes[0].Descriptor()
}

func (QueueStatus) Type() protoreflect.EnumType {
	return &file_server_api_proto_queue_v1_queue_proto_enumTypes[0]
}

func (x QueueStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueStatus.Descriptor instead.
func (QueueStatus) EnumDescriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{0}
}

type JoinQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinQueueRequest) Reset() {
	*x = JoinQueueRequest{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinQueueRequest) ProtoMessage() {}

func (x *JoinQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinQueueRequest.ProtoReflect.Descriptor instead.
func (*JoinQueueRequest) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{0}
}

func (x *JoinQueueRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *JoinQueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinQueueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{1}
}

func (x *GetPositionRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetPositionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueRequest) Reset() {
	*x = LeaveQueueRequest{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueRequest) ProtoMessage() {}

func (x *LeaveQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueRequest.ProtoReflect.Descriptor instead.
func (*LeaveQueueRequest) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveQueueRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *LeaveQueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveQueueResponse) Reset() {
	*x = LeaveQueueResponse{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveQueueResponse) ProtoMessage() {}

func (x *LeaveQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveQueueResponse.ProtoReflect.Descriptor instead.
func (*LeaveQueueResponse) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ConsumeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeTokenRequest) Reset() {
	*x = ConsumeTokenRequest{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeTokenRequest) ProtoMessage() {}

func (x *ConsumeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeTokenRequest.ProtoReflect.Descriptor instead.
func (*ConsumeTokenRequest) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ConsumeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeTokenResponse) Reset() {
	*x = ConsumeTokenResponse{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeTokenResponse) ProtoMessage() {}

func (x *ConsumeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeTokenResponse.ProtoReflect.Descriptor instead.
func (*ConsumeTokenResponse) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{7}
}

func (x *ConsumeTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetQueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatsRequest) Reset() {
	*x = GetQueueStatsRequest{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsRequest) ProtoMessage() {}

func (x *GetQueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{8}
}

func (x *GetQueueStatsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type ConfigureQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,2,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	BatchSize     int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	IntervalSecs  int32                  `protobuf:"varint,4,opt,name=interval_secs,json=intervalSecs,proto3" json:"interval_secs,omitempty"`
	TokenTtlSecs  int32                  `protobuf:"varint,5,opt,name=token_ttl_secs,json=tokenTtlSecs,proto3" json:"token_ttl_secs,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureQueueRequest) Reset() {
	*x = ConfigureQueueRequest{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureQueueRequest) ProtoMessage() {}

func (x *ConfigureQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureQueueRequest.ProtoReflect.Descriptor instead.
func (*ConfigureQueueRequest) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigureQueueRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ConfigureQueueRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *ConfigureQueueRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ConfigureQueueRequest) GetIntervalSecs() int32 {
	if x != nil {
		return x.IntervalSecs
	}
	return 0
}

func (x *ConfigureQueueRequest) GetTokenTtlSecs() int32 {
	if x != nil {
		return x.TokenTtlSecs
	}
	return 0
}

func (x *ConfigureQueueRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ConfigureQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureQueueResponse) Reset() {
	*x = ConfigureQueueResponse{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureQueueResponse) ProtoMessage() {}

func (x *ConfigureQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureQueueResponse.ProtoReflect.Descriptor instead.
func (*ConfigureQueueResponse) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigureQueueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type QueuePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int32                  `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	EstimatedWait int32                  `protobuf:"varint,2,opt,name=estimated_wait,json=estimatedWait,proto3" json:"estimated_wait,omitempty"` // seconds
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Status        QueueStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=queue.v1.QueueStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuePosition) Reset() {
	*x = QueuePosition{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePosition) ProtoMessage() {}

func (x *QueuePosition) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePosition.ProtoReflect.Descriptor instead.
func (*QueuePosition) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{11}
}

func (x *QueuePosition) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *QueuePosition) GetEstimatedWait() int32 {
	if x != nil {
		return x.EstimatedWait
	}
	return 0
}

func (x *QueuePosition) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *QueuePosition) GetStatus() QueueStatus {
	if x != nil {
		return x.Status
	}
	return QueueStatus_QUEUE_STATUS_UNSPECIFIED
}

type QueueStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TotalWaiting  int32                  `protobuf:"varint,2,opt,name=total_waiting,json=totalWaiting,proto3" json:"total_waiting,omitempty"`
	TotalAdmitted int32                  `protobuf:"varint,3,opt,name=total_admitted,json=totalAdmitted,proto3" json:"total_admitted,omitempty"`
	AvgWaitSecs   int32                  `protobuf:"varint,4,opt,name=avg_wait_secs,json=avgWaitSecs,proto3" json:"avg_wait_secs,omitempty"`
	AdmissionRate int32                  `protobuf:"varint,5,opt,name=admission_rate,json=admissionRate,proto3" json:"admission_rate,omitempty"` // per minute
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStats) Reset() {
	*x = QueueStats{}
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStats) ProtoMessage() {}

func (x *QueueStats) ProtoReflect() protoreflect.Message {
	mi := &file_server_api_proto_queue_v1_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStats.ProtoReflect.Descriptor instead.
func (*QueueStats) Descriptor() ([]byte, []int) {
	return file_server_api_proto_queue_v1_queue_proto_rawDescGZIP(), []int{12}
}

func (x *QueueStats) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *QueueStats) GetTotalWaiting() int32 {
	if x != nil {
		return x.TotalWaiting
	}
	return 0
}

func (x *QueueStats) GetTotalAdmitted() int32 {
	if x != nil {
		return x.TotalAdmitted
	}
	return 0
}

func (x *QueueStats) GetAvgWaitSecs() int32 {
	if x != nil {
		return x.AvgWaitSecs
	}
	return 0
}

func (x *QueueStats) GetAdmissionRate() int32 {
	if x != nil {
		return x.AdmissionRate
	}
	return 0
}

var File_server_api_proto_queue_v1_queue_proto protoreflect.FileDescriptor

const file_server_api_proto_queue_v1_queue_proto_rawDesc = "" +
	"\n" +
	"%server/api/proto/queue/v1/queue.proto\x12\bqueue.v1\"e\n" +
	"\x10JoinQueueRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"H\n" +
	"\x12GetPositionRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x11LeaveQueueRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12LeaveQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"a\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\"+\n" +
	"\x13ConsumeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"0\n" +
	"\x14ConsumeTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x14GetQueueStatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\xdd\x01\n" +
	"\x15ConfigureQueueRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12%\n" +
	"\x0emax_concurrent\x18\x02 \x01(\x05R\rmaxConcurrent\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\x12#\n" +
	"\rinterval_secs\x18\x04 \x01(\x05R\fintervalSecs\x12$\n" +
	"\x0etoken_ttl_secs\x18\x05 \x01(\x05R\ftokenTtlSecs\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"2\n" +
	"\x16ConfigureQueueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x97\x01\n" +
	"\rQueuePosition\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\x12%\n" +
	"\x0eestimated_wait\x18\x02 \x01(\x05R\restimatedWait\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.queue.v1.QueueStatusR\x06status\"\xbe\x01\n" +
	"\n" +
	"QueueStats\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12#\n" +
	"\rtotal_waiting\x18\x02 \x01(\x05R\ftotalWaiting\x12%\n" +
	"\x0etotal_admitted\x18\x03 \x01(\x05R\rtotalAdmitted\x12\"\n" +
	"\ravg_wait_secs\x18\x04 \x01(\x05R\vavgWaitSecs\x12%\n" +
	"\x0eadmission_rate\x18\x05 \x01(\x05R\radmissionRate*\x93\x01\n" +
	"\vQueueStatus\x12\x1c\n" +
	"\x18QUEUE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14QUEUE_STATUS_WAITING\x10\x01\x12\x16\n" +
	"\x12QUEUE_STATUS_READY\x10\x02\x12\x18\n" +
	"\x14QUEUE_STATUS_EXPIRED\x10\x03\x12\x1a\n" +
	"\x16QUEUE_STATUS_COMPLETED\x10\x042\x9c\x04\n" +
	"\fQueueService\x12@\n" +
	"\tJoinQueue\x12\x1a.queue.v1.JoinQueueRequest\x1a\x17.queue.v1.QueuePosition\x12D\n" +
	"\vGetPosition\x12\x1c.queue.v1.GetPositionRequest\x1a\x17.queue.v1.QueuePosition\x12G\n" +
	"\n" +
	"LeaveQueue\x12\x1b.queue.v1.LeaveQueueRequest\x1a\x1c.queue.v1.LeaveQueueResponse\x12P\n" +
	"\rValidateToken\x12\x1e.queue.v1.ValidateTokenRequest\x1a\x1f.queue.v1.ValidateTokenResponse\x12M\n" +
	"\fConsumeToken\x12\x1d.queue.v1.ConsumeTokenRequest\x1a\x1e.queue.v1.ConsumeTokenResponse\x12E\n" +
	"\rGetQueueStats\x12\x1e.queue.v1.GetQueueStatsRequest\x1a\x14.queue.v1.QueueStats\x12S\n" +
	"\x0eConfigureQueue\x12\x1f.queue.v1.ConfigureQueueRequest\x1a .queue.v1.ConfigureQueueResponseB8Z6github.com/MuhibNayem/Travio/server/api/proto/queue/v1b\x06proto3"

var (
	file_server_api_proto_queue_v1_queue_proto_rawDescOnce sync.Once
	file_server_api_proto_queue_v1_queue_proto_rawDescData []byte
)

func file_server_api_proto_queue_v1_queue_proto_rawDescGZIP() []byte {
	file_server_api_proto_queue_v1_queue_proto_rawDescOnce.Do(func() {
		file_server_api_proto_queue_v1_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_api_proto_queue_v1_queue_proto_rawDesc), len(file_server_api_proto_queue_v1_queue_proto_rawDesc)))
	})
	return file_server_api_proto_queue_v1_queue_proto_rawDescData
}

var file_server_api_proto_queue_v1_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_api_proto_queue_v1_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_server_api_proto_queue_v1_queue_proto_goTypes = []any{
	(QueueStatus)(0),               // 0: queue.v1.QueueStatus
	(*JoinQueueRequest)(nil),       // 1: queue.v1.JoinQueueRequest
	(*GetPositionRequest)(nil),     // 2: queue.v1.GetPositionRequest
	(*LeaveQueueRequest)(nil),      // 3: queue.v1.LeaveQueueRequest
	(*LeaveQueueResponse)(nil),     // 4: queue.v1.LeaveQueueResponse
	(*ValidateTokenRequest)(nil),   // 5: queue.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),  // 6: queue.v1.ValidateTokenResponse
	(*ConsumeTokenRequest)(nil),    // 7: queue.v1.ConsumeTokenRequest
	(*ConsumeTokenResponse)(nil),   // 8: queue.v1.ConsumeTokenResponse
	(*GetQueueStatsRequest)(nil),   // 9: queue.v1.GetQueueStatsRequest
	(*ConfigureQueueRequest)(nil),  // 10: queue.v1.ConfigureQueueRequest
	(*ConfigureQueueResponse)(nil), // 11: queue.v1.ConfigureQueueResponse
	(*QueuePosition)(nil),          // 12: queue.v1.QueuePosition
	(*QueueStats)(nil),             // 13: queue.v1.QueueStats
}
var file_server_api_proto_queue_v1_queue_proto_depIdxs = []int32{
	0,  // 0: queue.v1.QueuePosition.status:type_name -> queue.v1.QueueStatus
	1,  // 1: queue.v1.QueueService.JoinQueue:input_type -> queue.v1.JoinQueueRequest
	2,  // 2: queue.v1.QueueService.GetPosition:input_type -> queue.v1.GetPositionRequest
	3,  // 3: queue.v1.QueueService.LeaveQueue:input_type -> queue.v1.LeaveQueueRequest
	5,  // 4: queue.v1.QueueService.ValidateToken:input_type -> queue.v1.ValidateTokenRequest
	7,  // 5: queue.v1.QueueService.ConsumeToken:input_type -> queue.v1.ConsumeTokenRequest
	9,  // 6: queue.v1.QueueService.GetQueueStats:input_type -> queue.v1.GetQueueStatsRequest
	10, // 7: queue.v1.QueueService.ConfigureQueue:input_type -> queue.v1.ConfigureQueueRequest
	12, // 8: queue.v1.QueueService.JoinQueue:output_type -> queue.v1.QueuePosition
	12, // 9: queue.v1.QueueService.GetPosition:output_type -> queue.v1.QueuePosition
	4,  // 10: queue.v1.QueueService.LeaveQueue:output_type -> queue.v1.LeaveQueueResponse
	6,  // 11: queue.v1.QueueService.ValidateToken:output_type -> queue.v1.ValidateTokenResponse
	8,  // 12: queue.v1.QueueService.ConsumeToken:output_type -> queue.v1.ConsumeTokenResponse
	13, // 13: queue.v1.QueueService.GetQueueStats:output_type -> queue.v1.QueueStats
	11, // 14: queue.v1.QueueService.ConfigureQueue:output_type -> queue.v1.ConfigureQueueResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_server_api_proto_queue_v1_queue_proto_init() }
func file_server_api_proto_queue_v1_queue_proto_init() {
	if File_server_api_proto_queue_v1_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_api_proto_queue_v1_queue_proto_rawDesc), len(file_server_api_proto_queue_v1_queue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_api_proto_queue_v1_queue_proto_goTypes,
		DependencyIndexes: file_server_api_proto_queue_v1_queue_proto_depIdxs,
		EnumInfos:         file_server_api_proto_queue_v1_queue_proto_enumTypes,
		MessageInfos:      file_server_api_proto_queue_v1_queue_proto_msgTypes,
	}.Build()
	File_server_api_proto_queue_v1_queue_proto = out.File
	file_server_api_proto_queue_v1_queue_proto_goTypes = nil
	file_server_api_proto_queue_v1_queue_proto_depIdxs = nil
}
