// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/fraud/v1/fraud.proto

package fraudpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AnalyzeBookingRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TripId         string                 `protobuf:"bytes,4,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	// Passenger details
	PassengerNids  []string `protobuf:"bytes,5,rep,name=passenger_nids,json=passengerNids,proto3" json:"passenger_nids,omitempty"`
	PassengerNames []string `protobuf:"bytes,6,rep,name=passenger_names,json=passengerNames,proto3" json:"passenger_names,omitempty"`
	PassengerCount int32    `protobuf:"varint,7,opt,name=passenger_count,json=passengerCount,proto3" json:"passenger_count,omitempty"`
	// Booking behavior
	BookingTimestamp int64  `protobuf:"varint,8,opt,name=booking_timestamp,json=bookingTimestamp,proto3" json:"booking_timestamp,omitempty"`
	IpAddress        string `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent        string `protobuf:"bytes,10,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	PaymentMethod    string `protobuf:"bytes,11,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalAmountPaisa int64  `protobuf:"varint,12,opt,name=total_amount_paisa,json=totalAmountPaisa,proto3" json:"total_amount_paisa,omitempty"`
	// Historical context
	BookingsLast_24Hours int32 `protobuf:"varint,13,opt,name=bookings_last_24_hours,json=bookingsLast24Hours,proto3" json:"bookings_last_24_hours,omitempty"`
	BookingsLastWeek     int32 `protobuf:"varint,14,opt,name=bookings_last_week,json=bookingsLastWeek,proto3" json:"bookings_last_week,omitempty"`
	PreviousFraudFlags   int32 `protobuf:"varint,15,opt,name=previous_fraud_flags,json=previousFraudFlags,proto3" json:"previous_fraud_flags,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AnalyzeBookingRequest) Reset() {
	*x = AnalyzeBookingRequest{}
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBookingRequest) ProtoMessage() {}

func (x *AnalyzeBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBookingRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeBookingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{2}
}

func (x *AnalyzeBookingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AnalyzeBookingRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AnalyzeBookingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyzeBookingRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *AnalyzeBookingRequest) GetPassengerNids() []string {
	if x != nil {
		return x.PassengerNids
	}
	return nil
}

func (x *AnalyzeBookingRequest) GetPassengerNames() []string {
	if x != nil {
		return x.PassengerNames
	}
	return nil
}

func (x *AnalyzeBookingRequest) GetPassengerCount() int32 {
	if x != nil {
		return x.PassengerCount
	}
	return 0
}

func (x *AnalyzeBookingRequest) GetBookingTimestamp() int64 {
	if x != nil {
		return x.BookingTimestamp
	}
	return 0
}

func (x *AnalyzeBookingRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AnalyzeBookingRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AnalyzeBookingRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *AnalyzeBookingRequest) GetTotalAmountPaisa() int64 {
	if x != nil {
		return x.TotalAmountPaisa
	}
	return 0
}

func (x *AnalyzeBookingRequest) GetBookingsLast_24Hours() int32 {
	if x != nil {
		return x.BookingsLast_24Hours
	}
	return 0
}

func (x *AnalyzeBookingRequest) GetBookingsLastWeek() int32 {
	if x != nil {
		return x.BookingsLastWeek
	}
	return 0
}

func (x *AnalyzeBookingRequest) GetPreviousFraudFlags() int32 {
	if x != nil {
		return x.PreviousFraudFlags
	}
	return 0
}

type AnalyzeBookingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Risk score from 0-100 (higher = more risky)
	RiskScore int32 `protobuf:"varint,1,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	// Risk level: low, medium, high, critical
	RiskLevel string `protobuf:"bytes,2,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	// Confidence in the analysis (0-100)
	Confidence int32 `protobuf:"varint,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// Whether the transaction should be blocked
	ShouldBlock bool `protobuf:"varint,4,opt,name=should_block,json=shouldBlock,proto3" json:"should_block,omitempty"`
	// Specific risk factors identified
	RiskFactors []*RiskFactor `protobuf:"bytes,5,rep,name=risk_factors,json=riskFactors,proto3" json:"risk_factors,omitempty"`
	// Human-readable summary
	Summary string `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	// Model used for analysis
	Model         string `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeBookingResponse) Reset() {
	*x = AnalyzeBookingResponse{}
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeBookingResponse) ProtoMessage() {}

func (x *AnalyzeBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeBookingResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeBookingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeBookingResponse) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AnalyzeBookingResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *AnalyzeBookingResponse) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeBookingResponse) GetShouldBlock() bool {
	if x != nil {
		return x.ShouldBlock
	}
	return false
}

func (x *AnalyzeBookingResponse) GetRiskFactors() []*RiskFactor {
	if x != nil {
		return x.RiskFactors
	}
	return nil
}

func (x *AnalyzeBookingResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AnalyzeBookingResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type RiskFactor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // low, medium, high
	Score         int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`      // Contribution to total score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskFactor) Reset() {
	*x = RiskFactor{}
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskFactor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskFactor) ProtoMessage() {}

func (x *RiskFactor) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskFactor.ProtoReflect.Descriptor instead.
func (*RiskFactor) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{4}
}

func (x *RiskFactor) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RiskFactor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RiskFactor) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *RiskFactor) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type VerifyDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Document type: nid, passport
	DocumentType string `protobuf:"bytes,1,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	// Base64 encoded document image
	DocumentImage []byte `protobuf:"bytes,2,opt,name=document_image,json=documentImage,proto3" json:"document_image,omitempty"`
	// MIME type of the image
	ImageMimeType string `protobuf:"bytes,3,opt,name=image_mime_type,json=imageMimeType,proto3" json:"image_mime_type,omitempty"`
	// Expected NID for validation
	ExpectedNid string `protobuf:"bytes,4,opt,name=expected_nid,json=expectedNid,proto3" json:"expected_nid,omitempty"`
	// Expected name for validation
	ExpectedName string `protobuf:"bytes,5,opt,name=expected_name,json=expectedName,proto3" json:"expected_name,omitempty"`
	// Organization ID
	OrganizationId string `protobuf:"bytes,6,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyDocumentRequest) Reset() {
	*x = VerifyDocumentRequest{}
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDocumentRequest) ProtoMessage() {}

func (x *VerifyDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDocumentRequest.ProtoReflect.Descriptor instead.
func (*VerifyDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyDocumentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *VerifyDocumentRequest) GetDocumentImage() []byte {
	if x != nil {
		return x.DocumentImage
	}
	return nil
}

func (x *VerifyDocumentRequest) GetImageMimeType() string {
	if x != nil {
		return x.ImageMimeType
	}
	return ""
}

func (x *VerifyDocumentRequest) GetExpectedNid() string {
	if x != nil {
		return x.ExpectedNid
	}
	return ""
}

func (x *VerifyDocumentRequest) GetExpectedName() string {
	if x != nil {
		return x.ExpectedName
	}
	return ""
}

func (x *VerifyDocumentRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type VerifyDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAuthentic   bool                   `protobuf:"varint,1,opt,name=is_authentic,json=isAuthentic,proto3" json:"is_authentic,omitempty"`
	Confidence    int32                  `protobuf:"varint,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ExtractedNid  string                 `protobuf:"bytes,3,opt,name=extracted_nid,json=extractedNid,proto3" json:"extracted_nid,omitempty"`
	ExtractedName string                 `protobuf:"bytes,4,opt,name=extracted_name,json=extractedName,proto3" json:"extracted_name,omitempty"`
	// Tampering score 0-100 (higher = more tampering)
	TamperingScore int32    `protobuf:"varint,5,opt,name=tampering_score,json=tamperingScore,proto3" json:"tampering_score,omitempty"`
	Issues         []string `protobuf:"bytes,6,rep,name=issues,proto3" json:"issues,omitempty"`
	Summary        string   `protobuf:"bytes,7,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyDocumentResponse) Reset() {
	*x = VerifyDocumentResponse{}
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDocumentResponse) ProtoMessage() {}

func (x *VerifyDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fraud_v1_fraud_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDocumentResponse.ProtoReflect.Descriptor instead.
func (*VerifyDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyDocumentResponse) GetIsAuthentic() bool {
	if x != nil {
		return x.IsAuthentic
	}
	return false
}

func (x *VerifyDocumentResponse) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *VerifyDocumentResponse) GetExtractedNid() string {
	if x != nil {
		return x.ExtractedNid
	}
	return ""
}

func (x *VerifyDocumentResponse) GetExtractedName() string {
	if x != nil {
		return x.ExtractedName
	}
	return ""
}

func (x *VerifyDocumentResponse) GetTamperingScore() int32 {
	if x != nil {
		return x.TamperingScore
	}
	return 0
}

func (x *VerifyDocumentResponse) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *VerifyDocumentResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_api_proto_fraud_v1_fraud_proto protoreflect.FileDescriptor

const file_api_proto_fraud_v1_fraud_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/fraud/v1/fraud.proto\x12\bfraud.v1\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xdb\x04\n" +
	"\x15AnalyzeBookingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x17\n" +
	"\atrip_id\x18\x04 \x01(\tR\x06tripId\x12%\n" +
	"\x0epassenger_nids\x18\x05 \x03(\tR\rpassengerNids\x12'\n" +
	"\x0fpassenger_names\x18\x06 \x03(\tR\x0epassengerNames\x12'\n" +
	"\x0fpassenger_count\x18\a \x01(\x05R\x0epassengerCount\x12+\n" +
	"\x11booking_timestamp\x18\b \x01(\x03R\x10bookingTimestamp\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\n" +
	" \x01(\tR\tuserAgent\x12%\n" +
	"\x0epayment_method\x18\v \x01(\tR\rpaymentMethod\x12,\n" +
	"\x12total_amount_paisa\x18\f \x01(\x03R\x10totalAmountPaisa\x123\n" +
	"\x16bookings_last_24_hours\x18\r \x01(\x05R\x13bookingsLast24Hours\x12,\n" +
	"\x12bookings_last_week\x18\x0e \x01(\x05R\x10bookingsLastWeek\x120\n" +
	"\x14previous_fraud_flags\x18\x0f \x01(\x05R\x12previousFraudFlags\"\x82\x02\n" +
	"\x16AnalyzeBookingResponse\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x01 \x01(\x05R\triskScore\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x02 \x01(\tR\triskLevel\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x05R\n" +
	"confidence\x12!\n" +
	"\fshould_block\x18\x04 \x01(\bR\vshouldBlock\x127\n" +
	"\frisk_factors\x18\x05 \x03(\v2\x14.fraud.v1.RiskFactorR\vriskFactors\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\"t\n" +
	"\n" +
	"RiskFactor\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\"\xfc\x01\n" +
	"\x15VerifyDocumentRequest\x12#\n" +
	"\rdocument_type\x18\x01 \x01(\tR\fdocumentType\x12%\n" +
	"\x0edocument_image\x18\x02 \x01(\fR\rdocumentImage\x12&\n" +
	"\x0fimage_mime_type\x18\x03 \x01(\tR\rimageMimeType\x12!\n" +
	"\fexpected_nid\x18\x04 \x01(\tR\vexpectedNid\x12#\n" +
	"\rexpected_name\x18\x05 \x01(\tR\fexpectedName\x12'\n" +
	"\x0forganization_id\x18\x06 \x01(\tR\x0eorganizationId\"\x82\x02\n" +
	"\x16VerifyDocumentResponse\x12!\n" +
	"\fis_authentic\x18\x01 \x01(\bR\visAuthentic\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x05R\n" +
	"confidence\x12#\n" +
	"\rextracted_nid\x18\x03 \x01(\tR\fextractedNid\x12%\n" +
	"\x0eextracted_name\x18\x04 \x01(\tR\rextractedName\x12'\n" +
	"\x0ftampering_score\x18\x05 \x01(\x05R\x0etamperingScore\x12\x16\n" +
	"\x06issues\x18\x06 \x03(\tR\x06issues\x12\x18\n" +
	"\asummary\x18\a \x01(\tR\asummary2\xf5\x01\n" +
	"\fFraudService\x12S\n" +
	"\x0eAnalyzeBooking\x12\x1f.fraud.v1.AnalyzeBookingRequest\x1a .fraud.v1.AnalyzeBookingResponse\x12S\n" +
	"\x0eVerifyDocument\x12\x1f.fraud.v1.VerifyDocumentRequest\x1a .fraud.v1.VerifyDocumentResponse\x12;\n" +
	"\x06Health\x12\x17.fraud.v1.HealthRequest\x1a\x18.fraud.v1.HealthResponseB@Z>github.com/MuhibNayem/Travio/server/api/proto/fraud/v1;fraudpbb\x06proto3"

var (
	file_api_proto_fraud_v1_fraud_proto_rawDescOnce sync.Once
	file_api_proto_fraud_v1_fraud_proto_rawDescData []byte
)

func file_api_proto_fraud_v1_fraud_proto_rawDescGZIP() []byte {
	file_api_proto_fraud_v1_fraud_proto_rawDescOnce.Do(func() {
		file_api_proto_fraud_v1_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_fraud_v1_fraud_proto_rawDesc), len(file_api_proto_fraud_v1_fraud_proto_rawDesc)))
	})
	return file_api_proto_fraud_v1_fraud_proto_rawDescData
}

var file_api_proto_fraud_v1_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_fraud_v1_fraud_proto_goTypes = []any{
	(*HealthRequest)(nil),          // 0: fraud.v1.HealthRequest
	(*HealthResponse)(nil),         // 1: fraud.v1.HealthResponse
	(*AnalyzeBookingRequest)(nil),  // 2: fraud.v1.AnalyzeBookingRequest
	(*AnalyzeBookingResponse)(nil), // 3: fraud.v1.AnalyzeBookingResponse
	(*RiskFactor)(nil),             // 4: fraud.v1.RiskFactor
	(*VerifyDocumentRequest)(nil),  // 5: fraud.v1.VerifyDocumentRequest
	(*VerifyDocumentResponse)(nil), // 6: fraud.v1.VerifyDocumentResponse
}
var file_api_proto_fraud_v1_fraud_proto_depIdxs = []int32{
	4, // 0: fraud.v1.AnalyzeBookingResponse.risk_factors:type_name -> fraud.v1.RiskFactor
	2, // 1: fraud.v1.FraudService.AnalyzeBooking:input_type -> fraud.v1.AnalyzeBookingRequest
	5, // 2: fraud.v1.FraudService.VerifyDocument:input_type -> fraud.v1.VerifyDocumentRequest
	0, // 3: fraud.v1.FraudService.Health:input_type -> fraud.v1.HealthRequest
	3, // 4: fraud.v1.FraudService.AnalyzeBooking:output_type -> fraud.v1.AnalyzeBookingResponse
	6, // 5: fraud.v1.FraudService.VerifyDocument:output_type -> fraud.v1.VerifyDocumentResponse
	1, // 6: fraud.v1.FraudService.Health:output_type -> fraud.v1.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_fraud_v1_fraud_proto_init() }
func file_api_proto_fraud_v1_fraud_proto_init() {
	if File_api_proto_fraud_v1_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_fraud_v1_fraud_proto_rawDesc), len(file_api_proto_fraud_v1_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_fraud_v1_fraud_proto_goTypes,
		DependencyIndexes: file_api_proto_fraud_v1_fraud_proto_depIdxs,
		MessageInfos:      file_api_proto_fraud_v1_fraud_proto_msgTypes,
	}.Build()
	File_api_proto_fraud_v1_fraud_proto = out.File
	file_api_proto_fraud_v1_fraud_proto_goTypes = nil
	file_api_proto_fraud_v1_fraud_proto_depIdxs = nil
}
