// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/proto/audit/v1/audit.proto

package auditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AggregateId    string                 `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	EventType      string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ResourceType   string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Action         string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	ActorId        string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType      string                 `protobuf:"bytes,6,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	OrganizationId string                 `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IpAddress      string                 `protobuf:"bytes,8,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent      string                 `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Details        string                 `protobuf:"bytes,10,opt,name=details,proto3" json:"details,omitempty"` // JSON string
	Status         string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	FailureReason  string                 `protobuf:"bytes,12,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *LogRequest) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *LogRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LogRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *LogRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *LogRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *LogRequest) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *LogRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *LogRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *LogRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LogRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *LogRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogRequest) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *LogResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetByActorIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorId       string                 `protobuf:"bytes,1,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByActorIDRequest) Reset() {
	*x = GetByActorIDRequest{}
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByActorIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByActorIDRequest) ProtoMessage() {}

func (x *GetByActorIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByActorIDRequest.ProtoReflect.Descriptor instead.
func (*GetByActorIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *GetByActorIDRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *GetByActorIDRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetByActorIDRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetByResourceIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByResourceIDRequest) Reset() {
	*x = GetByResourceIDRequest{}
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByResourceIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByResourceIDRequest) ProtoMessage() {}

func (x *GetByResourceIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByResourceIDRequest.ProtoReflect.Descriptor instead.
func (*GetByResourceIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *GetByResourceIDRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetByResourceIDRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetByResourceIDRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetByTimeRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByTimeRangeRequest) Reset() {
	*x = GetByTimeRangeRequest{}
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByTimeRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTimeRangeRequest) ProtoMessage() {}

func (x *GetByTimeRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTimeRangeRequest.ProtoReflect.Descriptor instead.
func (*GetByTimeRangeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *GetByTimeRangeRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetByTimeRangeRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetByTimeRangeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetByTimeRangeRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsResponse) Reset() {
	*x = GetAuditLogsResponse{}
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsResponse) ProtoMessage() {}

func (x *GetAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_v1_audit_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuditLogsResponse) GetLogs() []*AuditLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetAuditLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AuditLog struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AggregateId    string                 `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	EventType      string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ResourceType   string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Action         string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ActorId        string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorType      string                 `protobuf:"bytes,7,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	OrganizationId string                 `protobuf:"bytes,8,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IpAddress      string                 `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent      string                 `protobuf:"bytes,10,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Details        string                 `protobuf:"bytes,11,opt,name=details,proto3" json:"details,omitempty"`
	Status         string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	FailureReason  string                 `protobuf:"bytes,13,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Archived       bool                   `protobuf:"varint,15,opt,name=archived,proto3" json:"archived,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_audit_v1_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_api_proto_audit_v1_audit_proto_rawDescGZIP(), []int{6}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *AuditLog) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AuditLog) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditLog) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditLog) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AuditLog) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AuditLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLog) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *AuditLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuditLog) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *AuditLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditLog) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

var File_api_proto_audit_v1_audit_proto protoreflect.FileDescriptor

const file_api_proto_audit_v1_audit_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/audit/v1/audit.proto\x12\baudit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\n" +
	"LogRequest\x12!\n" +
	"\faggregate_id\x18\x01 \x01(\tR\vaggregateId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x06 \x01(\tR\tactorType\x12'\n" +
	"\x0forganization_id\x18\a \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\b \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\x12\x18\n" +
	"\adetails\x18\n" +
	" \x01(\tR\adetails\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12%\n" +
	"\x0efailure_reason\x18\f \x01(\tR\rfailureReason\"7\n" +
	"\vLogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"^\n" +
	"\x13GetByActorIDRequest\x12\x19\n" +
	"\bactor_id\x18\x01 \x01(\tR\aactorId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"g\n" +
	"\x16GetByResourceIDRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xa1\x01\n" +
	"\x15GetByTimeRangeRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"T\n" +
	"\x14GetAuditLogsResponse\x12&\n" +
	"\x04logs\x18\x01 \x03(\v2\x12.audit.v1.AuditLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xea\x03\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\faggregate_id\x18\x02 \x01(\tR\vaggregateId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\a \x01(\tR\tactorType\x12'\n" +
	"\x0forganization_id\x18\b \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\n" +
	" \x01(\tR\tuserAgent\x12\x18\n" +
	"\adetails\x18\v \x01(\tR\adetails\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12%\n" +
	"\x0efailure_reason\x18\r \x01(\tR\rfailureReason\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\barchived\x18\x0f \x01(\bR\barchived2\xb9\x02\n" +
	"\fAuditService\x122\n" +
	"\x03Log\x12\x14.audit.v1.LogRequest\x1a\x15.audit.v1.LogResponse\x12M\n" +
	"\fGetByActorID\x12\x1d.audit.v1.GetByActorIDRequest\x1a\x1e.audit.v1.GetAuditLogsResponse\x12S\n" +
	"\x0fGetByResourceID\x12 .audit.v1.GetByResourceIDRequest\x1a\x1e.audit.v1.GetAuditLogsResponse\x12Q\n" +
	"\x0eGetByTimeRange\x12\x1f.audit.v1.GetByTimeRangeRequest\x1a\x1e.audit.v1.GetAuditLogsResponseB@Z>github.com/MuhibNayem/Travio/server/api/proto/audit/v1;auditv1b\x06proto3"

var (
	file_api_proto_audit_v1_audit_proto_rawDescOnce sync.Once
	file_api_proto_audit_v1_audit_proto_rawDescData []byte
)

func file_api_proto_audit_v1_audit_proto_rawDescGZIP() []byte {
	file_api_proto_audit_v1_audit_proto_rawDescOnce.Do(func() {
		file_api_proto_audit_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_audit_v1_audit_proto_rawDesc), len(file_api_proto_audit_v1_audit_proto_rawDesc)))
	})
	return file_api_proto_audit_v1_audit_proto_rawDescData
}

var file_api_proto_audit_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_audit_v1_audit_proto_goTypes = []any{
	(*LogRequest)(nil),             // 0: audit.v1.LogRequest
	(*LogResponse)(nil),            // 1: audit.v1.LogResponse
	(*GetByActorIDRequest)(nil),    // 2: audit.v1.GetByActorIDRequest
	(*GetByResourceIDRequest)(nil), // 3: audit.v1.GetByResourceIDRequest
	(*GetByTimeRangeRequest)(nil),  // 4: audit.v1.GetByTimeRangeRequest
	(*GetAuditLogsResponse)(nil),   // 5: audit.v1.GetAuditLogsResponse
	(*AuditLog)(nil),               // 6: audit.v1.AuditLog
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_api_proto_audit_v1_audit_proto_depIdxs = []int32{
	7, // 0: audit.v1.GetByTimeRangeRequest.from:type_name -> google.protobuf.Timestamp
	7, // 1: audit.v1.GetByTimeRangeRequest.to:type_name -> google.protobuf.Timestamp
	6, // 2: audit.v1.GetAuditLogsResponse.logs:type_name -> audit.v1.AuditLog
	7, // 3: audit.v1.AuditLog.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: audit.v1.AuditService.Log:input_type -> audit.v1.LogRequest
	2, // 5: audit.v1.AuditService.GetByActorID:input_type -> audit.v1.GetByActorIDRequest
	3, // 6: audit.v1.AuditService.GetByResourceID:input_type -> audit.v1.GetByResourceIDRequest
	4, // 7: audit.v1.AuditService.GetByTimeRange:input_type -> audit.v1.GetByTimeRangeRequest
	1, // 8: audit.v1.AuditService.Log:output_type -> audit.v1.LogResponse
	5, // 9: audit.v1.AuditService.GetByActorID:output_type -> audit.v1.GetAuditLogsResponse
	5, // 10: audit.v1.AuditService.GetByResourceID:output_type -> audit.v1.GetAuditLogsResponse
	5, // 11: audit.v1.AuditService.GetByTimeRange:output_type -> audit.v1.GetAuditLogsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_audit_v1_audit_proto_init() }
func file_api_proto_audit_v1_audit_proto_init() {
	if File_api_proto_audit_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_audit_v1_audit_proto_rawDesc), len(file_api_proto_audit_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_audit_v1_audit_proto_goTypes,
		DependencyIndexes: file_api_proto_audit_v1_audit_proto_depIdxs,
		MessageInfos:      file_api_proto_audit_v1_audit_proto_msgTypes,
	}.Build()
	File_api_proto_audit_v1_audit_proto = out.File
	file_api_proto_audit_v1_audit_proto_goTypes = nil
	file_api_proto_audit_v1_audit_proto_depIdxs = nil
}
