// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: api/proto/audit/v1/audit.proto

package auditv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditService_Log_FullMethodName             = "/audit.v1.AuditService/Log"
	AuditService_GetByActorID_FullMethodName    = "/audit.v1.AuditService/GetByActorID"
	AuditService_GetByResourceID_FullMethodName = "/audit.v1.AuditService/GetByResourceID"
	AuditService_GetByTimeRange_FullMethodName  = "/audit.v1.AuditService/GetByTimeRange"
)

// AuditServiceClient is the client API for AuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuditService provides write-only audit logging
type AuditServiceClient interface {
	// Log creates a new audit log entry (append-only)
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	// GetByActorID retrieves audit logs by actor ID
	GetByActorID(ctx context.Context, in *GetByActorIDRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error)
	// GetByResourceID retrieves audit logs by resource/aggregate ID
	GetByResourceID(ctx context.Context, in *GetByResourceIDRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error)
	// GetByTimeRange retrieves audit logs within a time range
	GetByTimeRange(ctx context.Context, in *GetByTimeRangeRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error)
}

type auditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditServiceClient(cc grpc.ClientConnInterface) AuditServiceClient {
	return &auditServiceClient{cc}
}

func (c *auditServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, AuditService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetByActorID(ctx context.Context, in *GetByActorIDRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogsResponse)
	err := c.cc.Invoke(ctx, AuditService_GetByActorID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetByResourceID(ctx context.Context, in *GetByResourceIDRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogsResponse)
	err := c.cc.Invoke(ctx, AuditService_GetByResourceID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *auditServiceClient) GetByTimeRange(ctx context.Context, in *GetByTimeRangeRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogsResponse)
	err := c.cc.Invoke(ctx, AuditService_GetByTimeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditServiceServer is the server API for AuditService service.
// All implementations must embed UnimplementedAuditServiceServer
// for forward compatibility.
//
// AuditService provides write-only audit logging
type AuditServiceServer interface {
	// Log creates a new audit log entry (append-only)
	Log(context.Context, *LogRequest) (*LogResponse, error)
	// GetByActorID retrieves audit logs by actor ID
	GetByActorID(context.Context, *GetByActorIDRequest) (*GetAuditLogsResponse, error)
	// GetByResourceID retrieves audit logs by resource/aggregate ID
	GetByResourceID(context.Context, *GetByResourceIDRequest) (*GetAuditLogsResponse, error)
	// GetByTimeRange retrieves audit logs within a time range
	GetByTimeRange(context.Context, *GetByTimeRangeRequest) (*GetAuditLogsResponse, error)
	mustEmbedUnimplementedAuditServiceServer()
}

// UnimplementedAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditServiceServer struct{}

func (UnimplementedAuditServiceServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedAuditServiceServer) GetByActorID(context.Context, *GetByActorIDRequest) (*GetAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByActorID not implemented")
}
func (UnimplementedAuditServiceServer) GetByResourceID(context.Context, *GetByResourceIDRequest) (*GetAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByResourceID not implemented")
}
func (UnimplementedAuditServiceServer) GetByTimeRange(context.Context, *GetByTimeRangeRequest) (*GetAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetByTimeRange not implemented")
}
func (UnimplementedAuditServiceServer) mustEmbedUnimplementedAuditServiceServer() {}
func (UnimplementedAuditServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditServiceServer will
// result in compilation errors.
type UnsafeAuditServiceServer interface {
	mustEmbedUnimplementedAuditServiceServer()
}

func RegisterAuditServiceServer(s grpc.ServiceRegistrar, srv AuditServiceServer) {
	// If the following call panics, it indicates UnimplementedAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditService_ServiceDesc, srv)
}

func _AuditService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetByActorID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByActorIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetByActorID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetByActorID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetByActorID(ctx, req.(*GetByActorIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetByResourceID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByResourceIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetByResourceID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetByResourceID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetByResourceID(ctx, req.(*GetByResourceIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuditService_GetByTimeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByTimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditServiceServer).GetByTimeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditService_GetByTimeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditServiceServer).GetByTimeRange(ctx, req.(*GetByTimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditService_ServiceDesc is the grpc.ServiceDesc for AuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audit.v1.AuditService",
	HandlerType: (*AuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _AuditService_Log_Handler,
		},
		{
			MethodName: "GetByActorID",
			Handler:    _AuditService_GetByActorID_Handler,
		},
		{
			MethodName: "GetByResourceID",
			Handler:    _AuditService_GetByResourceID_Handler,
		},
		{
			MethodName: "GetByTimeRange",
			Handler:    _AuditService_GetByTimeRange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/audit/v1/audit.proto",
}
