// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: payment/v1/payment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AmountPaisa    int64                  `protobuf:"varint,2,opt,name=amount_paisa,json=amountPaisa,proto3" json:"amount_paisa,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod  string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	CustomerName   string                 `protobuf:"bytes,5,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	CustomerEmail  string                 `protobuf:"bytes,6,opt,name=customer_email,json=customerEmail,proto3" json:"customer_email,omitempty"`
	CustomerPhone  string                 `protobuf:"bytes,7,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Description    string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	ReturnUrl      string                 `protobuf:"bytes,9,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	CancelUrl      string                 `protobuf:"bytes,10,opt,name=cancel_url,json=cancelUrl,proto3" json:"cancel_url,omitempty"`
	IpnUrl         string                 `protobuf:"bytes,11,opt,name=ipn_url,json=ipnUrl,proto3" json:"ipn_url,omitempty"`
	OrganizationId string                 `protobuf:"bytes,12,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmountPaisa() int64 {
	if x != nil {
		return x.AmountPaisa
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreatePaymentRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CreatePaymentRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

func (x *CreatePaymentRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *CreatePaymentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePaymentRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *CreatePaymentRequest) GetCancelUrl() string {
	if x != nil {
		return x.CancelUrl
	}
	return ""
}

func (x *CreatePaymentRequest) GetIpnUrl() string {
	if x != nil {
		return x.IpnUrl
	}
	return ""
}

func (x *CreatePaymentRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	Gateway       string                 `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreatePaymentResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *CreatePaymentResponse) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *CreatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VerifyPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       string                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPaymentRequest) Reset() {
	*x = VerifyPaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPaymentRequest) ProtoMessage() {}

func (x *VerifyPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyPaymentRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *VerifyPaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CapturePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       string                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapturePaymentRequest) Reset() {
	*x = CapturePaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePaymentRequest) ProtoMessage() {}

func (x *CapturePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePaymentRequest.ProtoReflect.Descriptor instead.
func (*CapturePaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CapturePaymentRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *CapturePaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type PaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	GatewayRef    string                 `protobuf:"bytes,2,opt,name=gateway_ref,json=gatewayRef,proto3" json:"gateway_ref,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AmountPaisa   int64                  `protobuf:"varint,4,opt,name=amount_paisa,json=amountPaisa,proto3" json:"amount_paisa,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	CardBrand     string                 `protobuf:"bytes,6,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardLast4     string                 `protobuf:"bytes,7,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	FailureReason string                 `protobuf:"bytes,8,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatusResponse) Reset() {
	*x = PaymentStatusResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatusResponse) ProtoMessage() {}

func (x *PaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*PaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PaymentStatusResponse) GetGatewayRef() string {
	if x != nil {
		return x.GatewayRef
	}
	return ""
}

func (x *PaymentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentStatusResponse) GetAmountPaisa() int64 {
	if x != nil {
		return x.AmountPaisa
	}
	return 0
}

func (x *PaymentStatusResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentStatusResponse) GetCardBrand() string {
	if x != nil {
		return x.CardBrand
	}
	return ""
}

func (x *PaymentStatusResponse) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *PaymentStatusResponse) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       string                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AmountPaisa   int64                  `protobuf:"varint,3,opt,name=amount_paisa,json=amountPaisa,proto3" json:"amount_paisa,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *RefundPaymentRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *RefundPaymentRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RefundPaymentRequest) GetAmountPaisa() int64 {
	if x != nil {
		return x.AmountPaisa
	}
	return 0
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefundId      string                 `protobuf:"bytes,1,opt,name=refund_id,json=refundId,proto3" json:"refund_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AmountPaisa   int64                  `protobuf:"varint,3,opt,name=amount_paisa,json=amountPaisa,proto3" json:"amount_paisa,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *RefundResponse) GetRefundId() string {
	if x != nil {
		return x.RefundId
	}
	return ""
}

func (x *RefundResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RefundResponse) GetAmountPaisa() int64 {
	if x != nil {
		return x.AmountPaisa
	}
	return 0
}

func (x *RefundResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type IPNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       string                 `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPNRequest) Reset() {
	*x = IPNRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPNRequest) ProtoMessage() {}

func (x *IPNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPNRequest.ProtoReflect.Descriptor instead.
func (*IPNRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *IPNRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *IPNRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IPNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPNResponse) Reset() {
	*x = IPNResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPNResponse) ProtoMessage() {}

func (x *IPNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPNResponse.ProtoReflect.Descriptor instead.
func (*IPNResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *IPNResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *IPNResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *IPNResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *IPNResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdatePaymentConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Gateway        string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"` // 'sslcommerz', 'bkash', 'nagad'
	Credentials    map[string]string      `protobuf:"bytes,3,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsActive       bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePaymentConfigRequest) Reset() {
	*x = UpdatePaymentConfigRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentConfigRequest) ProtoMessage() {}

func (x *UpdatePaymentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentConfigRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePaymentConfigRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdatePaymentConfigRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *UpdatePaymentConfigRequest) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *UpdatePaymentConfigRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdatePaymentConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentConfigResponse) Reset() {
	*x = UpdatePaymentConfigResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentConfigResponse) ProtoMessage() {}

func (x *UpdatePaymentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentConfigResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePaymentConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePaymentConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPaymentConfigRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentConfigRequest) Reset() {
	*x = GetPaymentConfigRequest{}
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentConfigRequest) ProtoMessage() {}

func (x *GetPaymentConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentConfigRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentConfigRequest) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{11}
}

func (x *GetPaymentConfigRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetPaymentConfigResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Gateway        string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	IsActive       bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPaymentConfigResponse) Reset() {
	*x = GetPaymentConfigResponse{}
	mi := &file_payment_v1_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentConfigResponse) ProtoMessage() {}

func (x *GetPaymentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_v1_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentConfigResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentConfigResponse) Descriptor() ([]byte, []int) {
	return file_payment_v1_payment_proto_rawDescGZIP(), []int{12}
}

func (x *GetPaymentConfigResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *GetPaymentConfigResponse) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *GetPaymentConfigResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_payment_v1_payment_proto protoreflect.FileDescriptor

const file_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x18payment/v1/payment.proto\x12\n" +
	"payment.v1\"\xac\x03\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12!\n" +
	"\famount_paisa\x18\x02 \x01(\x03R\vamountPaisa\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12#\n" +
	"\rcustomer_name\x18\x05 \x01(\tR\fcustomerName\x12%\n" +
	"\x0ecustomer_email\x18\x06 \x01(\tR\rcustomerEmail\x12%\n" +
	"\x0ecustomer_phone\x18\a \x01(\tR\rcustomerPhone\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"return_url\x18\t \x01(\tR\treturnUrl\x12\x1d\n" +
	"\n" +
	"cancel_url\x18\n" +
	" \x01(\tR\tcancelUrl\x12\x17\n" +
	"\aipn_url\x18\v \x01(\tR\x06ipnUrl\x12'\n" +
	"\x0forganization_id\x18\f \x01(\tR\x0eorganizationId\"\xaa\x01\n" +
	"\x15CreatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fredirect_url\x18\x03 \x01(\tR\vredirectUrl\x12\x18\n" +
	"\agateway\x18\x04 \x01(\tR\agateway\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"W\n" +
	"\x14VerifyPaymentRequest\x12\x18\n" +
	"\agateway\x18\x01 \x01(\tR\agateway\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"X\n" +
	"\x15CapturePaymentRequest\x12\x18\n" +
	"\agateway\x18\x01 \x01(\tR\agateway\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\x9b\x02\n" +
	"\x15PaymentStatusResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vgateway_ref\x18\x02 \x01(\tR\n" +
	"gatewayRef\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\famount_paisa\x18\x04 \x01(\x03R\vamountPaisa\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"card_brand\x18\x06 \x01(\tR\tcardBrand\x12\x1d\n" +
	"\n" +
	"card_last4\x18\a \x01(\tR\tcardLast4\x12%\n" +
	"\x0efailure_reason\x18\b \x01(\tR\rfailureReason\"\x92\x01\n" +
	"\x14RefundPaymentRequest\x12\x18\n" +
	"\agateway\x18\x01 \x01(\tR\agateway\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12!\n" +
	"\famount_paisa\x18\x03 \x01(\x03R\vamountPaisa\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x8f\x01\n" +
	"\x0eRefundResponse\x12\x1b\n" +
	"\trefund_id\x18\x01 \x01(\tR\brefundId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12!\n" +
	"\famount_paisa\x18\x03 \x01(\x03R\vamountPaisa\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"@\n" +
	"\n" +
	"IPNRequest\x12\x18\n" +
	"\agateway\x18\x01 \x01(\tR\agateway\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"}\n" +
	"\vIPNResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\x97\x02\n" +
	"\x1aUpdatePaymentConfigRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12Y\n" +
	"\vcredentials\x18\x03 \x03(\v27.payment.v1.UpdatePaymentConfigRequest.CredentialsEntryR\vcredentials\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x1bUpdatePaymentConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x17GetPaymentConfigRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"z\n" +
	"\x18GetPaymentConfigResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive2\xe8\x04\n" +
	"\x0ePaymentService\x12T\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a!.payment.v1.CreatePaymentResponse\x12T\n" +
	"\rVerifyPayment\x12 .payment.v1.VerifyPaymentRequest\x1a!.payment.v1.PaymentStatusResponse\x12V\n" +
	"\x0eCapturePayment\x12!.payment.v1.CapturePaymentRequest\x1a!.payment.v1.PaymentStatusResponse\x12M\n" +
	"\rRefundPayment\x12 .payment.v1.RefundPaymentRequest\x1a\x1a.payment.v1.RefundResponse\x12<\n" +
	"\tHandleIPN\x12\x16.payment.v1.IPNRequest\x1a\x17.payment.v1.IPNResponse\x12f\n" +
	"\x13UpdatePaymentConfig\x12&.payment.v1.UpdatePaymentConfigRequest\x1a'.payment.v1.UpdatePaymentConfigResponse\x12]\n" +
	"\x10GetPaymentConfig\x12#.payment.v1.GetPaymentConfigRequest\x1a$.payment.v1.GetPaymentConfigResponseB:Z8github.com/MuhibNayem/Travio/server/api/proto/payment/v1b\x06proto3"

var (
	file_payment_v1_payment_proto_rawDescOnce sync.Once
	file_payment_v1_payment_proto_rawDescData []byte
)

func file_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)))
	})
	return file_payment_v1_payment_proto_rawDescData
}

var file_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_payment_v1_payment_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),        // 0: payment.v1.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),       // 1: payment.v1.CreatePaymentResponse
	(*VerifyPaymentRequest)(nil),        // 2: payment.v1.VerifyPaymentRequest
	(*CapturePaymentRequest)(nil),       // 3: payment.v1.CapturePaymentRequest
	(*PaymentStatusResponse)(nil),       // 4: payment.v1.PaymentStatusResponse
	(*RefundPaymentRequest)(nil),        // 5: payment.v1.RefundPaymentRequest
	(*RefundResponse)(nil),              // 6: payment.v1.RefundResponse
	(*IPNRequest)(nil),                  // 7: payment.v1.IPNRequest
	(*IPNResponse)(nil),                 // 8: payment.v1.IPNResponse
	(*UpdatePaymentConfigRequest)(nil),  // 9: payment.v1.UpdatePaymentConfigRequest
	(*UpdatePaymentConfigResponse)(nil), // 10: payment.v1.UpdatePaymentConfigResponse
	(*GetPaymentConfigRequest)(nil),     // 11: payment.v1.GetPaymentConfigRequest
	(*GetPaymentConfigResponse)(nil),    // 12: payment.v1.GetPaymentConfigResponse
	nil,                                 // 13: payment.v1.UpdatePaymentConfigRequest.CredentialsEntry
}
var file_payment_v1_payment_proto_depIdxs = []int32{
	13, // 0: payment.v1.UpdatePaymentConfigRequest.credentials:type_name -> payment.v1.UpdatePaymentConfigRequest.CredentialsEntry
	0,  // 1: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	2,  // 2: payment.v1.PaymentService.VerifyPayment:input_type -> payment.v1.VerifyPaymentRequest
	3,  // 3: payment.v1.PaymentService.CapturePayment:input_type -> payment.v1.CapturePaymentRequest
	5,  // 4: payment.v1.PaymentService.RefundPayment:input_type -> payment.v1.RefundPaymentRequest
	7,  // 5: payment.v1.PaymentService.HandleIPN:input_type -> payment.v1.IPNRequest
	9,  // 6: payment.v1.PaymentService.UpdatePaymentConfig:input_type -> payment.v1.UpdatePaymentConfigRequest
	11, // 7: payment.v1.PaymentService.GetPaymentConfig:input_type -> payment.v1.GetPaymentConfigRequest
	1,  // 8: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.CreatePaymentResponse
	4,  // 9: payment.v1.PaymentService.VerifyPayment:output_type -> payment.v1.PaymentStatusResponse
	4,  // 10: payment.v1.PaymentService.CapturePayment:output_type -> payment.v1.PaymentStatusResponse
	6,  // 11: payment.v1.PaymentService.RefundPayment:output_type -> payment.v1.RefundResponse
	8,  // 12: payment.v1.PaymentService.HandleIPN:output_type -> payment.v1.IPNResponse
	10, // 13: payment.v1.PaymentService.UpdatePaymentConfig:output_type -> payment.v1.UpdatePaymentConfigResponse
	12, // 14: payment.v1.PaymentService.GetPaymentConfig:output_type -> payment.v1.GetPaymentConfigResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_payment_v1_payment_proto_init() }
func file_payment_v1_payment_proto_init() {
	if File_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_payment_proto_rawDesc), len(file_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_payment_v1_payment_proto = out.File
	file_payment_v1_payment_proto_goTypes = nil
	file_payment_v1_payment_proto_depIdxs = nil
}
