// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/pricing/v1/pricing.proto

package pricingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculatePriceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TripId         string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	SeatClass      string                 `protobuf:"bytes,2,opt,name=seat_class,json=seatClass,proto3" json:"seat_class,omitempty"`
	Date           string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Quantity       int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	BasePricePaisa int64                  `protobuf:"varint,5,opt,name=base_price_paisa,json=basePricePaisa,proto3" json:"base_price_paisa,omitempty"`
	OccupancyRate  float64                `protobuf:"fixed64,6,opt,name=occupancy_rate,json=occupancyRate,proto3" json:"occupancy_rate,omitempty"`
	OrganizationId string                 `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // For operator-specific overrides
	DepartureTime  int64                  `protobuf:"varint,8,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`   // Unix timestamp (seconds)
	RouteId        string                 `protobuf:"bytes,9,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	ScheduleId     string                 `protobuf:"bytes,10,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	FromStationId  string                 `protobuf:"bytes,11,opt,name=from_station_id,json=fromStationId,proto3" json:"from_station_id,omitempty"`
	ToStationId    string                 `protobuf:"bytes,12,opt,name=to_station_id,json=toStationId,proto3" json:"to_station_id,omitempty"`
	SeatCategory   string                 `protobuf:"bytes,13,opt,name=seat_category,json=seatCategory,proto3" json:"seat_category,omitempty"`
	VehicleType    string                 `protobuf:"bytes,14,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	VehicleClass   string                 `protobuf:"bytes,15,opt,name=vehicle_class,json=vehicleClass,proto3" json:"vehicle_class,omitempty"`
	PromoCode      string                 `protobuf:"bytes,16,opt,name=promo_code,json=promoCode,proto3" json:"promo_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CalculatePriceRequest) Reset() {
	*x = CalculatePriceRequest{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceRequest) ProtoMessage() {}

func (x *CalculatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceRequest.ProtoReflect.Descriptor instead.
func (*CalculatePriceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePriceRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CalculatePriceRequest) GetSeatClass() string {
	if x != nil {
		return x.SeatClass
	}
	return ""
}

func (x *CalculatePriceRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CalculatePriceRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CalculatePriceRequest) GetBasePricePaisa() int64 {
	if x != nil {
		return x.BasePricePaisa
	}
	return 0
}

func (x *CalculatePriceRequest) GetOccupancyRate() float64 {
	if x != nil {
		return x.OccupancyRate
	}
	return 0
}

func (x *CalculatePriceRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CalculatePriceRequest) GetDepartureTime() int64 {
	if x != nil {
		return x.DepartureTime
	}
	return 0
}

func (x *CalculatePriceRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *CalculatePriceRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *CalculatePriceRequest) GetFromStationId() string {
	if x != nil {
		return x.FromStationId
	}
	return ""
}

func (x *CalculatePriceRequest) GetToStationId() string {
	if x != nil {
		return x.ToStationId
	}
	return ""
}

func (x *CalculatePriceRequest) GetSeatCategory() string {
	if x != nil {
		return x.SeatCategory
	}
	return ""
}

func (x *CalculatePriceRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CalculatePriceRequest) GetVehicleClass() string {
	if x != nil {
		return x.VehicleClass
	}
	return ""
}

func (x *CalculatePriceRequest) GetPromoCode() string {
	if x != nil {
		return x.PromoCode
	}
	return ""
}

type CalculatePriceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FinalPricePaisa int64                  `protobuf:"varint,1,opt,name=final_price_paisa,json=finalPricePaisa,proto3" json:"final_price_paisa,omitempty"`
	BasePricePaisa  int64                  `protobuf:"varint,2,opt,name=base_price_paisa,json=basePricePaisa,proto3" json:"base_price_paisa,omitempty"`
	AppliedRules    []*AppliedRule         `protobuf:"bytes,3,rep,name=applied_rules,json=appliedRules,proto3" json:"applied_rules,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CalculatePriceResponse) Reset() {
	*x = CalculatePriceResponse{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceResponse) ProtoMessage() {}

func (x *CalculatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceResponse.ProtoReflect.Descriptor instead.
func (*CalculatePriceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePriceResponse) GetFinalPricePaisa() int64 {
	if x != nil {
		return x.FinalPricePaisa
	}
	return 0
}

func (x *CalculatePriceResponse) GetBasePricePaisa() int64 {
	if x != nil {
		return x.BasePricePaisa
	}
	return 0
}

func (x *CalculatePriceResponse) GetAppliedRules() []*AppliedRule {
	if x != nil {
		return x.AppliedRules
	}
	return nil
}

type AppliedRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Multiplier    float64                `protobuf:"fixed64,3,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedRule) Reset() {
	*x = AppliedRule{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedRule) ProtoMessage() {}

func (x *AppliedRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedRule.ProtoReflect.Descriptor instead.
func (*AppliedRule) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{2}
}

func (x *AppliedRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AppliedRule) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *AppliedRule) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

type PricingRule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // Null/Empty for Global
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Condition       string                 `protobuf:"bytes,5,opt,name=condition,proto3" json:"condition,omitempty"`
	Multiplier      float64                `protobuf:"fixed64,6,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	AdjustmentType  string                 `protobuf:"bytes,7,opt,name=adjustment_type,json=adjustmentType,proto3" json:"adjustment_type,omitempty"`      // multiplier, additive, override
	AdjustmentValue float64                `protobuf:"fixed64,8,opt,name=adjustment_value,json=adjustmentValue,proto3" json:"adjustment_value,omitempty"` // When adjustment_type != multiplier
	Priority        int32                  `protobuf:"varint,9,opt,name=priority,proto3" json:"priority,omitempty"`
	IsActive        bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PricingRule) Reset() {
	*x = PricingRule{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingRule) ProtoMessage() {}

func (x *PricingRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingRule.ProtoReflect.Descriptor instead.
func (*PricingRule) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{3}
}

func (x *PricingRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PricingRule) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *PricingRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PricingRule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PricingRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *PricingRule) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *PricingRule) GetAdjustmentType() string {
	if x != nil {
		return x.AdjustmentType
	}
	return ""
}

func (x *PricingRule) GetAdjustmentValue() float64 {
	if x != nil {
		return x.AdjustmentValue
	}
	return 0
}

func (x *PricingRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PricingRule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PricingRule) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PricingRule) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetRulesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeInactive bool                   `protobuf:"varint,1,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	OrganizationId  string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // Filter
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRulesRequest) Reset() {
	*x = GetRulesRequest{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesRequest) ProtoMessage() {}

func (x *GetRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesRequest.ProtoReflect.Descriptor instead.
func (*GetRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{4}
}

func (x *GetRulesRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

func (x *GetRulesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*PricingRule         `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRulesResponse) Reset() {
	*x = GetRulesResponse{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRulesResponse) ProtoMessage() {}

func (x *GetRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRulesResponse.ProtoReflect.Descriptor instead.
func (*GetRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{5}
}

func (x *GetRulesResponse) GetRules() []*PricingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CreateRuleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Condition       string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Multiplier      float64                `protobuf:"fixed64,5,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	AdjustmentType  string                 `protobuf:"bytes,6,opt,name=adjustment_type,json=adjustmentType,proto3" json:"adjustment_type,omitempty"`
	AdjustmentValue float64                `protobuf:"fixed64,7,opt,name=adjustment_value,json=adjustmentValue,proto3" json:"adjustment_value,omitempty"`
	Priority        int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRuleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRuleRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *CreateRuleRequest) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *CreateRuleRequest) GetAdjustmentType() string {
	if x != nil {
		return x.AdjustmentType
	}
	return ""
}

func (x *CreateRuleRequest) GetAdjustmentValue() float64 {
	if x != nil {
		return x.AdjustmentValue
	}
	return 0
}

func (x *CreateRuleRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type CreateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PricingRule           `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleResponse) Reset() {
	*x = CreateRuleResponse{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleResponse) ProtoMessage() {}

func (x *CreateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRuleResponse) GetRule() *PricingRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type UpdateRuleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Condition       string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Multiplier      float64                `protobuf:"fixed64,5,opt,name=multiplier,proto3" json:"multiplier,omitempty"`
	AdjustmentType  string                 `protobuf:"bytes,6,opt,name=adjustment_type,json=adjustmentType,proto3" json:"adjustment_type,omitempty"`
	AdjustmentValue float64                `protobuf:"fixed64,7,opt,name=adjustment_value,json=adjustmentValue,proto3" json:"adjustment_value,omitempty"`
	Priority        int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	IsActive        bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRuleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRuleRequest) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *UpdateRuleRequest) GetMultiplier() float64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *UpdateRuleRequest) GetAdjustmentType() string {
	if x != nil {
		return x.AdjustmentType
	}
	return ""
}

func (x *UpdateRuleRequest) GetAdjustmentValue() float64 {
	if x != nil {
		return x.AdjustmentValue
	}
	return 0
}

func (x *UpdateRuleRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateRuleRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PricingRule           `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleResponse) Reset() {
	*x = UpdateRuleResponse{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleResponse) ProtoMessage() {}

func (x *UpdateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRuleResponse) GetRule() *PricingRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRuleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pricing_v1_pricing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pricing_v1_pricing_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_pricing_v1_pricing_proto protoreflect.FileDescriptor

const file_api_proto_pricing_v1_pricing_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/pricing/v1/pricing.proto\x12\n" +
	"pricing.v1\"\xb4\x04\n" +
	"\x15CalculatePriceRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1d\n" +
	"\n" +
	"seat_class\x18\x02 \x01(\tR\tseatClass\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12(\n" +
	"\x10base_price_paisa\x18\x05 \x01(\x03R\x0ebasePricePaisa\x12%\n" +
	"\x0eoccupancy_rate\x18\x06 \x01(\x01R\roccupancyRate\x12'\n" +
	"\x0forganization_id\x18\a \x01(\tR\x0eorganizationId\x12%\n" +
	"\x0edeparture_time\x18\b \x01(\x03R\rdepartureTime\x12\x19\n" +
	"\broute_id\x18\t \x01(\tR\arouteId\x12\x1f\n" +
	"\vschedule_id\x18\n" +
	" \x01(\tR\n" +
	"scheduleId\x12&\n" +
	"\x0ffrom_station_id\x18\v \x01(\tR\rfromStationId\x12\"\n" +
	"\rto_station_id\x18\f \x01(\tR\vtoStationId\x12#\n" +
	"\rseat_category\x18\r \x01(\tR\fseatCategory\x12!\n" +
	"\fvehicle_type\x18\x0e \x01(\tR\vvehicleType\x12#\n" +
	"\rvehicle_class\x18\x0f \x01(\tR\fvehicleClass\x12\x1d\n" +
	"\n" +
	"promo_code\x18\x10 \x01(\tR\tpromoCode\"\xac\x01\n" +
	"\x16CalculatePriceResponse\x12*\n" +
	"\x11final_price_paisa\x18\x01 \x01(\x03R\x0ffinalPricePaisa\x12(\n" +
	"\x10base_price_paisa\x18\x02 \x01(\x03R\x0ebasePricePaisa\x12<\n" +
	"\rapplied_rules\x18\x03 \x03(\v2\x17.pricing.v1.AppliedRuleR\fappliedRules\"c\n" +
	"\vAppliedRule\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x03 \x01(\x01R\n" +
	"multiplier\"\x85\x03\n" +
	"\vPricingRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcondition\x18\x05 \x01(\tR\tcondition\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x06 \x01(\x01R\n" +
	"multiplier\x12'\n" +
	"\x0fadjustment_type\x18\a \x01(\tR\x0eadjustmentType\x12)\n" +
	"\x10adjustment_value\x18\b \x01(\x01R\x0fadjustmentValue\x12\x1a\n" +
	"\bpriority\x18\t \x01(\x05R\bpriority\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\"e\n" +
	"\x0fGetRulesRequest\x12)\n" +
	"\x10include_inactive\x18\x01 \x01(\bR\x0fincludeInactive\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"A\n" +
	"\x10GetRulesResponse\x12-\n" +
	"\x05rules\x18\x01 \x03(\v2\x17.pricing.v1.PricingRuleR\x05rules\"\xa0\x02\n" +
	"\x11CreateRuleRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x05 \x01(\x01R\n" +
	"multiplier\x12'\n" +
	"\x0fadjustment_type\x18\x06 \x01(\tR\x0eadjustmentType\x12)\n" +
	"\x10adjustment_value\x18\a \x01(\x01R\x0fadjustmentValue\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\"A\n" +
	"\x12CreateRuleResponse\x12+\n" +
	"\x04rule\x18\x01 \x01(\v2\x17.pricing.v1.PricingRuleR\x04rule\"\xa4\x02\n" +
	"\x11UpdateRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x05 \x01(\x01R\n" +
	"multiplier\x12'\n" +
	"\x0fadjustment_type\x18\x06 \x01(\tR\x0eadjustmentType\x12)\n" +
	"\x10adjustment_value\x18\a \x01(\x01R\x0fadjustmentValue\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\"A\n" +
	"\x12UpdateRuleResponse\x12+\n" +
	"\x04rule\x18\x01 \x01(\v2\x17.pricing.v1.PricingRuleR\x04rule\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x97\x03\n" +
	"\x0ePricingService\x12W\n" +
	"\x0eCalculatePrice\x12!.pricing.v1.CalculatePriceRequest\x1a\".pricing.v1.CalculatePriceResponse\x12E\n" +
	"\bGetRules\x12\x1b.pricing.v1.GetRulesRequest\x1a\x1c.pricing.v1.GetRulesResponse\x12K\n" +
	"\n" +
	"CreateRule\x12\x1d.pricing.v1.CreateRuleRequest\x1a\x1e.pricing.v1.CreateRuleResponse\x12K\n" +
	"\n" +
	"UpdateRule\x12\x1d.pricing.v1.UpdateRuleRequest\x1a\x1e.pricing.v1.UpdateRuleResponse\x12K\n" +
	"\n" +
	"DeleteRule\x12\x1d.pricing.v1.DeleteRuleRequest\x1a\x1e.pricing.v1.DeleteRuleResponseBDZBgithub.com/MuhibNayem/Travio/server/api/proto/pricing/v1;pricingv1b\x06proto3"

var (
	file_api_proto_pricing_v1_pricing_proto_rawDescOnce sync.Once
	file_api_proto_pricing_v1_pricing_proto_rawDescData []byte
)

func file_api_proto_pricing_v1_pricing_proto_rawDescGZIP() []byte {
	file_api_proto_pricing_v1_pricing_proto_rawDescOnce.Do(func() {
		file_api_proto_pricing_v1_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_pricing_v1_pricing_proto_rawDesc), len(file_api_proto_pricing_v1_pricing_proto_rawDesc)))
	})
	return file_api_proto_pricing_v1_pricing_proto_rawDescData
}

var file_api_proto_pricing_v1_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_pricing_v1_pricing_proto_goTypes = []any{
	(*CalculatePriceRequest)(nil),  // 0: pricing.v1.CalculatePriceRequest
	(*CalculatePriceResponse)(nil), // 1: pricing.v1.CalculatePriceResponse
	(*AppliedRule)(nil),            // 2: pricing.v1.AppliedRule
	(*PricingRule)(nil),            // 3: pricing.v1.PricingRule
	(*GetRulesRequest)(nil),        // 4: pricing.v1.GetRulesRequest
	(*GetRulesResponse)(nil),       // 5: pricing.v1.GetRulesResponse
	(*CreateRuleRequest)(nil),      // 6: pricing.v1.CreateRuleRequest
	(*CreateRuleResponse)(nil),     // 7: pricing.v1.CreateRuleResponse
	(*UpdateRuleRequest)(nil),      // 8: pricing.v1.UpdateRuleRequest
	(*UpdateRuleResponse)(nil),     // 9: pricing.v1.UpdateRuleResponse
	(*DeleteRuleRequest)(nil),      // 10: pricing.v1.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),     // 11: pricing.v1.DeleteRuleResponse
}
var file_api_proto_pricing_v1_pricing_proto_depIdxs = []int32{
	2,  // 0: pricing.v1.CalculatePriceResponse.applied_rules:type_name -> pricing.v1.AppliedRule
	3,  // 1: pricing.v1.GetRulesResponse.rules:type_name -> pricing.v1.PricingRule
	3,  // 2: pricing.v1.CreateRuleResponse.rule:type_name -> pricing.v1.PricingRule
	3,  // 3: pricing.v1.UpdateRuleResponse.rule:type_name -> pricing.v1.PricingRule
	0,  // 4: pricing.v1.PricingService.CalculatePrice:input_type -> pricing.v1.CalculatePriceRequest
	4,  // 5: pricing.v1.PricingService.GetRules:input_type -> pricing.v1.GetRulesRequest
	6,  // 6: pricing.v1.PricingService.CreateRule:input_type -> pricing.v1.CreateRuleRequest
	8,  // 7: pricing.v1.PricingService.UpdateRule:input_type -> pricing.v1.UpdateRuleRequest
	10, // 8: pricing.v1.PricingService.DeleteRule:input_type -> pricing.v1.DeleteRuleRequest
	1,  // 9: pricing.v1.PricingService.CalculatePrice:output_type -> pricing.v1.CalculatePriceResponse
	5,  // 10: pricing.v1.PricingService.GetRules:output_type -> pricing.v1.GetRulesResponse
	7,  // 11: pricing.v1.PricingService.CreateRule:output_type -> pricing.v1.CreateRuleResponse
	9,  // 12: pricing.v1.PricingService.UpdateRule:output_type -> pricing.v1.UpdateRuleResponse
	11, // 13: pricing.v1.PricingService.DeleteRule:output_type -> pricing.v1.DeleteRuleResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_pricing_v1_pricing_proto_init() }
func file_api_proto_pricing_v1_pricing_proto_init() {
	if File_api_proto_pricing_v1_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_pricing_v1_pricing_proto_rawDesc), len(file_api_proto_pricing_v1_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_pricing_v1_pricing_proto_goTypes,
		DependencyIndexes: file_api_proto_pricing_v1_pricing_proto_depIdxs,
		MessageInfos:      file_api_proto_pricing_v1_pricing_proto_msgTypes,
	}.Build()
	File_api_proto_pricing_v1_pricing_proto = out.File
	file_api_proto_pricing_v1_pricing_proto_goTypes = nil
	file_api_proto_pricing_v1_pricing_proto_depIdxs = nil
}
