// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/fleet/v1/fleet.proto

package fleetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED AssetType = 0
	AssetType_ASSET_TYPE_BUS         AssetType = 1
	AssetType_ASSET_TYPE_TRAIN       AssetType = 2
	AssetType_ASSET_TYPE_LAUNCH      AssetType = 3
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_BUS",
		2: "ASSET_TYPE_TRAIN",
		3: "ASSET_TYPE_LAUNCH",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED": 0,
		"ASSET_TYPE_BUS":         1,
		"ASSET_TYPE_TRAIN":       2,
		"ASSET_TYPE_LAUNCH":      3,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_fleet_v1_fleet_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_api_proto_fleet_v1_fleet_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{0}
}

type AssetStatus int32

const (
	AssetStatus_ASSET_STATUS_ACTIVE      AssetStatus = 0
	AssetStatus_ASSET_STATUS_MAINTENANCE AssetStatus = 1
	AssetStatus_ASSET_STATUS_RETIRED     AssetStatus = 2
)

// Enum value maps for AssetStatus.
var (
	AssetStatus_name = map[int32]string{
		0: "ASSET_STATUS_ACTIVE",
		1: "ASSET_STATUS_MAINTENANCE",
		2: "ASSET_STATUS_RETIRED",
	}
	AssetStatus_value = map[string]int32{
		"ASSET_STATUS_ACTIVE":      0,
		"ASSET_STATUS_MAINTENANCE": 1,
		"ASSET_STATUS_RETIRED":     2,
	}
)

func (x AssetStatus) Enum() *AssetStatus {
	p := new(AssetStatus)
	*p = x
	return p
}

func (x AssetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_fleet_v1_fleet_proto_enumTypes[1].Descriptor()
}

func (AssetStatus) Type() protoreflect.EnumType {
	return &file_api_proto_fleet_v1_fleet_proto_enumTypes[1]
}

func (x AssetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetStatus.Descriptor instead.
func (AssetStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{1}
}

type Asset struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Type           AssetType              `protobuf:"varint,3,opt,name=type,proto3,enum=fleet.v1.AssetType" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Vin            string                 `protobuf:"bytes,6,opt,name=vin,proto3" json:"vin,omitempty"`
	Make           string                 `protobuf:"bytes,7,opt,name=make,proto3" json:"make,omitempty"`
	Model          string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	Year           int32                  `protobuf:"varint,9,opt,name=year,proto3" json:"year,omitempty"`
	Status         AssetStatus            `protobuf:"varint,10,opt,name=status,proto3,enum=fleet.v1.AssetStatus" json:"status,omitempty"`
	Config         *Config                `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"` // JSON string for specific layouts (seats, decks)
	CreatedAt      string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Asset) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Asset) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Asset) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Asset) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Asset) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Asset) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_ACTIVE
}

func (x *Asset) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Asset) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Asset) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Arbitrary JSON or explicit fields
	LayoutType    string `protobuf:"bytes,1,opt,name=layout_type,json=layoutType,proto3" json:"layout_type,omitempty"` // "2+2", "Sleeping_Cabin"
	Features      string `protobuf:"bytes,2,opt,name=features,proto3" json:"features,omitempty"`                       // "Wifi, AC"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetLayoutType() string {
	if x != nil {
		return x.LayoutType
	}
	return ""
}

func (x *Config) GetFeatures() string {
	if x != nil {
		return x.Features
	}
	return ""
}

type RegisterAssetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           AssetType              `protobuf:"varint,3,opt,name=type,proto3,enum=fleet.v1.AssetType" json:"type,omitempty"`
	LicensePlate   string                 `protobuf:"bytes,4,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Vin            string                 `protobuf:"bytes,5,opt,name=vin,proto3" json:"vin,omitempty"`
	Make           string                 `protobuf:"bytes,6,opt,name=make,proto3" json:"make,omitempty"`
	Model          string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	Year           int32                  `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	Status         AssetStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=fleet.v1.AssetStatus" json:"status,omitempty"`
	Config         *Config                `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterAssetRequest) Reset() {
	*x = RegisterAssetRequest{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAssetRequest) ProtoMessage() {}

func (x *RegisterAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAssetRequest.ProtoReflect.Descriptor instead.
func (*RegisterAssetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAssetRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *RegisterAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAssetRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *RegisterAssetRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *RegisterAssetRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *RegisterAssetRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *RegisterAssetRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterAssetRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *RegisterAssetRequest) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_ACTIVE
}

func (x *RegisterAssetRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetAssetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAssetRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type UpdateAssetStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Status         AssetStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=fleet.v1.AssetStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAssetStatusRequest) Reset() {
	*x = UpdateAssetStatusRequest{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetStatusRequest) ProtoMessage() {}

func (x *UpdateAssetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAssetStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAssetStatusRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateAssetStatusRequest) GetStatus() AssetStatus {
	if x != nil {
		return x.Status
	}
	return AssetStatus_ASSET_STATUS_ACTIVE
}

type AssetLocation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssetId        string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Latitude       float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed          float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading        float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	Timestamp      string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssetLocation) Reset() {
	*x = AssetLocation{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetLocation) ProtoMessage() {}

func (x *AssetLocation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetLocation.ProtoReflect.Descriptor instead.
func (*AssetLocation) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *AssetLocation) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetLocation) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AssetLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *AssetLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *AssetLocation) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *AssetLocation) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *AssetLocation) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type UpdateLocationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AssetId        string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Latitude       float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed          float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading        float64                `protobuf:"fixed64,6,opt,name=heading,proto3" json:"heading,omitempty"`
	Timestamp      string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLocationRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *UpdateLocationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *UpdateLocationRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *UpdateLocationRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *GetLocationRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type StreamLocationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // Stream all assets for an org
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamLocationsRequest) Reset() {
	*x = StreamLocationsRequest{}
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLocationsRequest) ProtoMessage() {}

func (x *StreamLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fleet_v1_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLocationsRequest.ProtoReflect.Descriptor instead.
func (*StreamLocationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fleet_v1_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *StreamLocationsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

var File_api_proto_fleet_v1_fleet_proto protoreflect.FileDescriptor

const file_api_proto_fleet_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/fleet/v1/fleet.proto\x12\bfleet.v1\"\x89\x03\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.fleet.v1.AssetTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\x12\x10\n" +
	"\x03vin\x18\x06 \x01(\tR\x03vin\x12\x12\n" +
	"\x04make\x18\a \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\t \x01(\x05R\x04year\x12-\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x15.fleet.v1.AssetStatusR\x06status\x12(\n" +
	"\x06config\x18\v \x01(\v2\x10.fleet.v1.ConfigR\x06config\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"E\n" +
	"\x06Config\x12\x1f\n" +
	"\vlayout_type\x18\x01 \x01(\tR\n" +
	"layoutType\x12\x1a\n" +
	"\bfeatures\x18\x02 \x01(\tR\bfeatures\"\xca\x02\n" +
	"\x14RegisterAssetRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.fleet.v1.AssetTypeR\x04type\x12#\n" +
	"\rlicense_plate\x18\x04 \x01(\tR\flicensePlate\x12\x10\n" +
	"\x03vin\x18\x05 \x01(\tR\x03vin\x12\x12\n" +
	"\x04make\x18\x06 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\b \x01(\x05R\x04year\x12-\n" +
	"\x06status\x18\t \x01(\x0e2\x15.fleet.v1.AssetStatusR\x06status\x12(\n" +
	"\x06config\x18\n" +
	" \x01(\v2\x10.fleet.v1.ConfigR\x06config\"J\n" +
	"\x0fGetAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\"\x82\x01\n" +
	"\x18UpdateAssetStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.fleet.v1.AssetStatusR\x06status\"\xdb\x01\n" +
	"\rAssetLocation\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\"\xe3\x01\n" +
	"\x15UpdateLocationRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x06 \x01(\x01R\aheading\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\"2\n" +
	"\x16UpdateLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x12GetLocationRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\"A\n" +
	"\x16StreamLocationsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId*h\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eASSET_TYPE_BUS\x10\x01\x12\x14\n" +
	"\x10ASSET_TYPE_TRAIN\x10\x02\x12\x15\n" +
	"\x11ASSET_TYPE_LAUNCH\x10\x03*^\n" +
	"\vAssetStatus\x12\x17\n" +
	"\x13ASSET_STATUS_ACTIVE\x10\x00\x12\x1c\n" +
	"\x18ASSET_STATUS_MAINTENANCE\x10\x01\x12\x18\n" +
	"\x14ASSET_STATUS_RETIRED\x10\x022\xbd\x03\n" +
	"\fFleetService\x12@\n" +
	"\rRegisterAsset\x12\x1e.fleet.v1.RegisterAssetRequest\x1a\x0f.fleet.v1.Asset\x126\n" +
	"\bGetAsset\x12\x19.fleet.v1.GetAssetRequest\x1a\x0f.fleet.v1.Asset\x12H\n" +
	"\x11UpdateAssetStatus\x12\".fleet.v1.UpdateAssetStatusRequest\x1a\x0f.fleet.v1.Asset\x12S\n" +
	"\x0eUpdateLocation\x12\x1f.fleet.v1.UpdateLocationRequest\x1a .fleet.v1.UpdateLocationResponse\x12D\n" +
	"\vGetLocation\x12\x1c.fleet.v1.GetLocationRequest\x1a\x17.fleet.v1.AssetLocation\x12N\n" +
	"\x0fStreamLocations\x12 .fleet.v1.StreamLocationsRequest\x1a\x17.fleet.v1.AssetLocation0\x01B@Z>github.com/MuhibNayem/Travio/server/api/proto/fleet/v1;fleetv1b\x06proto3"

var (
	file_api_proto_fleet_v1_fleet_proto_rawDescOnce sync.Once
	file_api_proto_fleet_v1_fleet_proto_rawDescData []byte
)

func file_api_proto_fleet_v1_fleet_proto_rawDescGZIP() []byte {
	file_api_proto_fleet_v1_fleet_proto_rawDescOnce.Do(func() {
		file_api_proto_fleet_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_fleet_v1_fleet_proto_rawDesc), len(file_api_proto_fleet_v1_fleet_proto_rawDesc)))
	})
	return file_api_proto_fleet_v1_fleet_proto_rawDescData
}

var file_api_proto_fleet_v1_fleet_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_fleet_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_fleet_v1_fleet_proto_goTypes = []any{
	(AssetType)(0),                   // 0: fleet.v1.AssetType
	(AssetStatus)(0),                 // 1: fleet.v1.AssetStatus
	(*Asset)(nil),                    // 2: fleet.v1.Asset
	(*Config)(nil),                   // 3: fleet.v1.Config
	(*RegisterAssetRequest)(nil),     // 4: fleet.v1.RegisterAssetRequest
	(*GetAssetRequest)(nil),          // 5: fleet.v1.GetAssetRequest
	(*UpdateAssetStatusRequest)(nil), // 6: fleet.v1.UpdateAssetStatusRequest
	(*AssetLocation)(nil),            // 7: fleet.v1.AssetLocation
	(*UpdateLocationRequest)(nil),    // 8: fleet.v1.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),   // 9: fleet.v1.UpdateLocationResponse
	(*GetLocationRequest)(nil),       // 10: fleet.v1.GetLocationRequest
	(*StreamLocationsRequest)(nil),   // 11: fleet.v1.StreamLocationsRequest
}
var file_api_proto_fleet_v1_fleet_proto_depIdxs = []int32{
	0,  // 0: fleet.v1.Asset.type:type_name -> fleet.v1.AssetType
	1,  // 1: fleet.v1.Asset.status:type_name -> fleet.v1.AssetStatus
	3,  // 2: fleet.v1.Asset.config:type_name -> fleet.v1.Config
	0,  // 3: fleet.v1.RegisterAssetRequest.type:type_name -> fleet.v1.AssetType
	1,  // 4: fleet.v1.RegisterAssetRequest.status:type_name -> fleet.v1.AssetStatus
	3,  // 5: fleet.v1.RegisterAssetRequest.config:type_name -> fleet.v1.Config
	1,  // 6: fleet.v1.UpdateAssetStatusRequest.status:type_name -> fleet.v1.AssetStatus
	4,  // 7: fleet.v1.FleetService.RegisterAsset:input_type -> fleet.v1.RegisterAssetRequest
	5,  // 8: fleet.v1.FleetService.GetAsset:input_type -> fleet.v1.GetAssetRequest
	6,  // 9: fleet.v1.FleetService.UpdateAssetStatus:input_type -> fleet.v1.UpdateAssetStatusRequest
	8,  // 10: fleet.v1.FleetService.UpdateLocation:input_type -> fleet.v1.UpdateLocationRequest
	10, // 11: fleet.v1.FleetService.GetLocation:input_type -> fleet.v1.GetLocationRequest
	11, // 12: fleet.v1.FleetService.StreamLocations:input_type -> fleet.v1.StreamLocationsRequest
	2,  // 13: fleet.v1.FleetService.RegisterAsset:output_type -> fleet.v1.Asset
	2,  // 14: fleet.v1.FleetService.GetAsset:output_type -> fleet.v1.Asset
	2,  // 15: fleet.v1.FleetService.UpdateAssetStatus:output_type -> fleet.v1.Asset
	9,  // 16: fleet.v1.FleetService.UpdateLocation:output_type -> fleet.v1.UpdateLocationResponse
	7,  // 17: fleet.v1.FleetService.GetLocation:output_type -> fleet.v1.AssetLocation
	7,  // 18: fleet.v1.FleetService.StreamLocations:output_type -> fleet.v1.AssetLocation
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_fleet_v1_fleet_proto_init() }
func file_api_proto_fleet_v1_fleet_proto_init() {
	if File_api_proto_fleet_v1_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_fleet_v1_fleet_proto_rawDesc), len(file_api_proto_fleet_v1_fleet_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_fleet_v1_fleet_proto_goTypes,
		DependencyIndexes: file_api_proto_fleet_v1_fleet_proto_depIdxs,
		EnumInfos:         file_api_proto_fleet_v1_fleet_proto_enumTypes,
		MessageInfos:      file_api_proto_fleet_v1_fleet_proto_msgTypes,
	}.Build()
	File_api_proto_fleet_v1_fleet_proto = out.File
	file_api_proto_fleet_v1_fleet_proto_goTypes = nil
	file_api_proto_fleet_v1_fleet_proto_depIdxs = nil
}
